### ISSUE TITLE
Validari campuri - PrestaShop 1.4.9.0

### ISSUE THREAD

**Issue by gabispanu** [Smart2Pay/PrestaShop#4]
Mediu de Test : PrestaShop  1.4.9.0

Actiuni : 
1. Din PrestaShop Admin-> Module-> Smart2Pay, am sters MID-ul si am dat Save
   Rezultat-> "Fatal error: Class 'Translate' not found in /data/phpprojects/prestashop/1_4_9_0/modules/smart2pay/smart2pay.php on line 918"

Nota*:  apare aceasta eroare cand lipseste unul din campurile mandatory si se incearca sa se salveze

**Comment by andys2p** [comment]
Fixuit si testat.
